ARREJS-14: Rejseplan in admin
os2display/display-admin-client pull request #141
Opened 2022-04-26 08:18 UTC by sinejespersen

#### Link to ticket

Please add a link to the ticket being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2022-04-27 15:22 UTC, tuj requested changes

2022-04-27 15:22 UTC, tuj commented on src/components/slide/content/station/station-selector.jsx
> +      .catch(() => {});
Show error message to user.

2022-04-28 07:14 UTC, sinejespersen commented on src/components/slide/content/station/station-selector.jsx
> +      .catch(() => {});
Will fix

2022-04-28 11:26 UTC, tuj approved these changes

2022-04-28 12:48 UTC, merged