2927: Started work on upgrading poster component to work with v2 api
os2display/display-admin-client pull request #271
Opened 2024-11-22 11:51 UTC by tuj

#### Link to ticket

Please add a link to the ticket being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2025-02-03 13:28 UTC, sinejespersen commented on src/components/slide/content/feed-selector.jsx
> +      for (let i = 0; i < targets.length; i += 1) {
why not foreach?

2025-02-03 13:32 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +  /* eslint-disable jsx-a11y/control-has-associated-label */
why?

2025-02-03 13:35 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +                    <strong>{t("chosen-occurrence")}:</strong>{" "}
```suggestion
                    <b>{t("chosen-occurrence")}:</b>{" "}
```

2025-02-03 13:36 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +import PropTypes from "prop-types";
Consider breaking this file up, very long.

2025-02-03 13:39 UTC, sinejespersen commented on src/components/slide/content/poster/poster-subscription.jsx
> +    const places = subscriptionPlaceValue.map((option) => option.value);
```suggestion
    const places = subscriptionPlaceValue.map(({ value }) => value);
```

2025-02-03 13:39 UTC, sinejespersen commented on src/components/slide/content/poster/poster-subscription.jsx
> +    const tags = subscriptionTagValue.map((option) => option.value);
```suggestion
    const tags = subscriptionTagValue.map(({ value }) =>value);
```

2025-02-03 13:42 UTC, sinejespersen commented on src/components/slide/content/poster/poster-subscription.jsx
> +  const numberOptions = Array.from(Array(10).keys());
perhaps a comment to explain.....

2025-02-04 08:09 UTC, sinejespersen commented on src/components/slide/content/poster/poster-subscription.jsx
> +      timeoutRef.current = setTimeout(() => {
why the timeout?

2025-02-04 08:10 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +  /* eslint-enable jsx-a11y/control-has-associated-label */
why?

2025-02-04 08:11 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +                      {singleSelectedEvent?.occurrences?.map((occurrence) => (
```suggestion
                      {singleSelectedEvent?.occurrences?.map(( {entityId, start, ticketPriceRange} ) => (
```

2025-02-04 08:17 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +                        style={{ cursor: "pointer" }}
perhaps generalize this https://github.com/os2display/display-admin-client/blob/c01afab8d626bf39d216903e934f47f60922598a/src/components/util/table/table-header.scss#L2

2025-02-04 08:19 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +function PosterSingle({ configurationChange, feedSource, configuration }) {
I would destructure ```configuration```

2025-02-04 08:21 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +function PosterSingle({ configurationChange, feedSource, configuration }) {
perhaps also the other ones?

2025-02-04 08:27 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +                        onClick={() => handleSelectEvent(searchEvent)}
This should be a button

2025-02-04 08:28 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +                              alt={searchEvent?.title}
I have a hard time figuring out what this this does. click something and search something - anyways - the `alt` text is probably wrong, but perhaps you can show me the ui and explain what it does?

2025-02-04 08:29 UTC, sinejespersen requested changes
a bunch of comments, do you have time to show me the ui?

2025-02-04 13:32 UTC, tuj commented on src/components/slide/content/poster/poster-single.jsx
> +function PosterSingle({ configurationChange, feedSource, configuration }) {
done

2025-02-04 13:32 UTC, tuj commented on src/components/slide/content/poster/poster-subscription.jsx
> +  const numberOptions = Array.from(Array(10).keys());
added

2025-02-04 13:44 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +  const {
This can be done directly in the `function PosterSingle({ ...blabla....` but this is fine to

2025-02-04 13:44 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +                    <b>Valgt begivenhed:</b> {singleSelectedEvent.title} (
`t("Valgt begivenhed:")`

2025-02-04 13:45 UTC, sinejespersen approved these changes
two more comments and approved

2025-02-05 18:15 UTC, sinejespersen commented on src/components/slide/content/poster/poster-single.jsx
> +export default PosterSingle;
🎉

2025-02-05 18:16 UTC, sinejespersen submitted a review, later dismissed

2025-03-18 10:59 UTC, merged